FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json /app/
RUN npm install

COPY frontend /app

ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
