FROM node:20-alpine AS deps

WORKDIR /app

COPY frontend/package*.json /app/
RUN npm ci


FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
COPY frontend /app

ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1

RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1

COPY --from=builder /app/public /app/public
COPY --from=builder /app/.next/standalone /app/
COPY --from=builder /app/.next/static /app/.next/static

EXPOSE 3000

CMD ["node", "server.js"]
